<?php

namespace Image\GalleryBundle\Entity\Repository;

/**
 * AlbumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbumRepository extends \Doctrine\ORM\EntityRepository
{
    public function getOneAlbum($AlbumId)
    {
        $qb = $this->createQueryBuilder('a')
            ->select('a.id', 'a.name')
            ->addOrderBy('a.name', 'ASC')
            ->setParameter('a.id', $AlbumId)
        ;

        return $qb->getQuery()->getResult();
    }

    public function getSomeImgFromAlbum($NumImg)
    {
//        $qb_1 = $this->createQueryBuilder('a')
//            ->select('a.images')
//            ->limit($NumImg)//количество картинок
//            ->getQuery();

        $qb = $this->createQueryBuilder('a')
            ->select('a.id', 'a.name', 'a.images')
//            ->where('COUNT(a.images) = 5') //выберет записи где количество картинок равно пяти
//            ->limit($NumImg)              //количество записей альбома
            ->addOrderBy('a.name', 'ASC')
            ->groupBy('a.id')
            ->having('COUNT(a.images) = 5') //тоже, только те записа, где количество картинок равно 5
        ;

        return $qb->getQuery()->getResult();
    }
}